version: 1
log: info

via: &viaanchor
  target: www.test1.com:4433
  headers:
    Proxy-Authorization: basic ${ENCODED_PW}
    Proxy-KeepAlive: true
    Host: www.test1.com:4433

servers:
  first_server:
    listen:
      - "127.0.0.1:8080"
    tls: true # Enable TLS features like SNI filtering
    sni:
      www.test1.com: proxy-via
    default: echo
    # note yet implemented
    maxclients: 2
    via:
      *viaanchor

  health-server:
    listen: [ "127.0.0.1:8081" ]
    default: health
    maxclients: 1
    via:
      *viaanchor

upstream:
  proxy-via: "tcp://127.0.0.1:3128"
